version: '3.8'

services:
  app:
    # Use the pre-built image from Docker Hub
    image: enda2020/portfolio-app:latest
    # Name the container for easier management
    container_name: portfolio-container
    ports:
      - "5001:5001"
    volumes:
      # Mount the local './data' directory to the '/app/data' directory in the container.
      # This makes the database file directly accessible on your host machine for easy backups.
      - ./data:/app/data
    restart: unless-stopped