version: '3.8'

services:
  app:
    # Build the Docker image from the Dockerfile in the current directory
    build: .
    # Name the container for easier management
    container_name: portfolio-container
    ports:
      - "5001:5001"
    volumes:
      # Mount the local './data' directory to the '/app/data' directory in the container.
      # This makes the database file directly accessible on your host machine for easy backups.
      - ./data:/app/data
    restart: unless-stopped